### ISSUE TITLE
Fix headers

### ISSUE THREAD

**Issue by Puigcerber** [Backbase/backbase.github.io#128]
Currently he `h3` looks bigger than the `h2`:
![Screenshot 2024-05-16 at 10 53 23](https://github.com/Backbase/backbase.github.io/assets/866808/d6f60950-8bcf-49c4-b543-7ec0cebeaeff)

`h2` with `font: 500 20px / 32px Libre Franklin;` renders at `20px` while `h3` with `font: 700 1.2em / 1 Libre Franklin;` renders at `23.04px`. Also the `font-weight` for the `h3` is `700` and `500` for the `h2`.

**Comment by robinsonzimmermann** [comment]
Fixed with #137
